version: '3'

services:

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 45432:5432

  websocket:
    build: .
    volumes:
      - .:/opt/app
    depends_on:
      - db
    command: daphne -b 127.0.0.1 -p 8001 meduserstore.asgi:application

  api:
    build: .
    volumes:
      - .:/opt/app
    depends_on:
      - db
    command: gunicorn -b 127.0.0.1:8000 meduserstore.wsgi


volumes:
  db:
