version: '3'

services:

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 45432:5432

  websocket:
    build: .
    volumes:
      - .:/opt/app
    depends_on:
      - db
    ports:
      - 8001:8000
    command: daphne -b 0.0.0.0 -p 8000 meduserstore.asgi:application

  api:
    build: .
    volumes:
      - .:/opt/app
    depends_on:
      - db
    ports:
      - 8000:8000
    command: gunicorn -b 0.0.0.0:8000 meduserstore.wsgi


volumes:
  db:
