# Generated by Django 3.0.4 on 2020-04-01 17:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('add_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('dmed_url', models.TextField(blank=True, null=True)),
                ('dmed_priority', models.IntegerField(default=0)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=300, verbose_name='полное имя')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='M/F - муж/жен', max_length=10, verbose_name='пол')),
                ('birth_date', models.DateField(help_text='YYYY-MM-DD', verbose_name='дата рождения')),
                ('iin', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='ИИН')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия')),
                ('first_name', models.TextField(blank=True, max_length=100, null=True, verbose_name='имя')),
                ('second_name', models.TextField(blank=True, max_length=100, null=True, verbose_name='отчество')),
                ('contact_numbers', models.CharField(blank=True, help_text='можно несколько через запятые', max_length=128, null=True, verbose_name='контактные номера телефона')),
                ('residence_place', models.CharField(blank=True, max_length=512, null=True, verbose_name='место проживания')),
                ('study_place', models.CharField(blank=True, max_length=512, null=True, verbose_name='место учебы')),
                ('working_place', models.CharField(blank=True, max_length=512, null=True, verbose_name='место работы')),
                ('had_contact_with_infected', models.BooleanField(blank=True, null=True, verbose_name='имел контакт с инфицированным')),
                ('been_abroad_last_month', models.BooleanField(blank=True, null=True, verbose_name='был за рубежом последний месяц')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='дополнительно')),
                ('dmed_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID в DMED')),
                ('dmed_rpn_id', models.BigIntegerField(blank=True, null=True)),
                ('dmed_master_data_id', models.BigIntegerField(blank=True, null=True)),
                ('citizenship', models.ForeignKey(blank=True, help_text='гражданин какой страны?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country')),
                ('dmed_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('add_date', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('persons', models.ManyToManyField(blank=True, related_name='markers', to='core.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckpointPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('source_place', models.CharField(blank=True, max_length=512, null=True, verbose_name='исходный пункт')),
                ('destination_place', models.CharField(blank=True, max_length=512, null=True, verbose_name='пункт назначения')),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Checkpoint')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='инспектор')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Region'),
        ),
        migrations.AddField(
            model_name='user',
            name='checkpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Checkpoint'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
