# Generated by Django 3.0.4 on 2020-04-01 17:13

from django.db import migrations


# RUN 0001 FIRST
# СНАЧАЛА ВЫПОЛНИТЕ МИГРАЦИЮ ДО 0001


def default_groups_and_perms(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    P = apps.get_model('auth', 'Permission')

    inspectors = Group.objects.create(name='inspectors')
    inspectors.permissions.add(P.objects.get(codename='view_checkpoint'))

    inspectors.permissions.add(P.objects.get(codename='add_checkpointpass'))
    inspectors.permissions.add(P.objects.get(codename='change_checkpointpass'))
    inspectors.permissions.add(P.objects.get(codename='view_checkpointpass'))

    inspectors.permissions.add(P.objects.get(codename='view_country'))

    inspectors.permissions.add(P.objects.get(codename='view_marker'))

    inspectors.permissions.add(P.objects.get(codename='add_person'))
    inspectors.permissions.add(P.objects.get(codename='change_person'))
    inspectors.permissions.add(P.objects.get(codename='view_person'))

    inspectors.permissions.add(P.objects.get(codename='view_region'))


def default_regions(apps, schema_editor):
    Region = apps.get_model('core', 'Region')
    Country = apps.get_model('core', 'Country')
    kz = Country.objects.get(pk='KZ')

    for r in [
        Region(name='АКМОЛИНСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-akm.dmed.kz/WebApi2.3/api/'),
        Region(name='АКТЮБИНСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-akt.dmed.kz/WebApi2.3/api/'),
        Region(name='АЛМАТИНСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-ala.dmed.kz/WebApi2.3/api/'),
        Region(name='АТЫРАУСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-atr.dmed.kz/WebApi2.3/api/'),
        Region(name='ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-zko.dmed.kz/WebApi2.3/api/'),
        Region(name='ЖАМБЫЛСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-zha.dmed.kz/WebApi2.3/api/'),
        Region(name='КАРАГАНДИНСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-krg.dmed.kz/WebApi2.3/api/'),
        Region(name='КОСТАНАЙСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-kos.dmed.kz/WebApi2.3/api/'),
        Region(name='КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-kzy.dmed.kz/WebApi2.3/api/'),
        Region(name='МАНГИСТАУСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-mng.dmed.kz/WebApi2.3/api/'),
        Region(name='ЮЖНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-uko.dmed.kz/WebApi2.3/api/'),
        Region(name='ПАВЛОДАРСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-pvd.dmed.kz/WebApi2.3/api/'),
        Region(name='СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-sko.dmed.kz/WebApi2.3/api/'),
        Region(name='ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', country=kz, dmed_url='https://lkp-vko.dmed.kz/WebApi2.3/api/'),
        Region(name='АЛМАТЫ', country=kz, dmed_url='https://lkp-alm.dmed.kz/WebApi2.3/api/'),
        Region(name='АСТАНА', country=kz, dmed_url='https://lkp-ast.dmed.kz/WebApi2.3/api/')
    ]:
        r.name = r.name.capitalize()
        r.save()


def default_countries(apps, schema_editor):
    Country = apps.get_model('core', 'Country')
    for code, name in (
        ('KZ', 'Казахстан'),
        ('RU', 'Россия'),
        ('CN', 'Китай'),
        ('UZ', 'Узбекистан'),
        ('KR', 'Киргизия'),
        ('TRK', 'Туркменистан')
    ):
        Country.objects.create(code=code, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_countries),
        migrations.RunPython(default_regions),
        migrations.RunPython(default_groups_and_perms),
    ]
