# Generated by Django 3.0.4 on 2020-03-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_working_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointpass',
            name='destination_place',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='пункт назначения'),
        ),
        migrations.AlterField(
            model_name='checkpointpass',
            name='source_place',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='исходный пункт'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence_place',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='место проживания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='study_place',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='место учебы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='working_place',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='место работы'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
