# Generated by Django 3.0.5 on 2020-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200408_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointpass',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='passes', through='core.PersonPassData', to='core.Person'),
        ),
        migrations.AddConstraint(
            model_name='personpassdata',
            constraint=models.UniqueConstraint(fields=('person', 'checkpoint_pass'), name='checkpointpass_person_unique'),
        ),
    ]
