# Generated by Django 3.0.4 on 2020-04-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200402_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
