# Generated by Django 3.0.5 on 2020-04-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200408_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpassdata',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
