# Generated by Django 3.0.4 on 2020-04-03 05:45

from django.db import migrations

OTHER_CIA = (
    6,     # Азербайджан
    1006,  # Азербайджан
    16,    # Армения
    1016,  # Армения
    1023,  # Белоруссия
    1105,  # Киргизия
    1132,  # Молдавия
    1194,  # Таджикистан
    1205,  # Туркмения,
    1208,  # Узбекистан
)


def set_country_priorities(apps, schema_editor):
    Country = apps.get_model('core', 'Country')

    Country.objects.filter(id__in=(85, 1085)).update(priority=40)  # Казахстан
    Country.objects.filter(id__in=(166, 1166)).update(priority=30)  # РФ
    Country.objects.filter(id=1209).update(priority=29)  # Украина
    Country.objects.filter(id__in=OTHER_CIA).update(priority=20)  # СНГ


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_priority'),
    ]

    operations = [
        migrations.RunPython(set_country_priorities)
    ]
