# Generated by Django 3.0.5 on 2020-04-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200409_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameracapture',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='checkpointpass',
            name='policeman',
        ),
        migrations.AddField(
            model_name='camera',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Checkpoint'),
        ),
        migrations.AddField(
            model_name='cameracapture',
            name='checkpoint_pass',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_capture', to='core.CheckpointPass'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Policeman',
        ),
    ]
