# Generated by Django 3.0.5 on 2020-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cameracapture_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameracapture',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='captures', to='core.Person'),
        ),
    ]
