# Generated by Django 3.0.5 on 2020-04-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200417_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointpass',
            name='direction',
        ),
    ]
